name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        macos-args: [--target x86_64-apple-darwin, --target aarch64-apple-darwin]
        exclude:
          - os: ubuntu-latest
            macos-args: --target aarch64-apple-darwin
          - os: windows-latest
            macos-args: --target aarch64-apple-darwin
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: rustc --print target-list
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install maturin
#     - name: Build
#       run: maturin build --release
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release -i python${{ matrix.python-version }}
      if: matrix.os != "macos-latest"
    - uses: PyO3/maturin-action@v1
      with:
        command: build
        args: --release -i python${{ matrix.python-version }} --target ${{ matrix.macos-args }}
      if: matrix.os == "macos-latest"
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }} ${{ matrix.python-version }} wheels
        path: target/wheels
